// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myrvakwtnwcrafkpeonj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cnZha3d0bndjcmFma3Blb25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NzI4NzUsImV4cCI6MjA1NzI0ODg3NX0.l27DblFqFTBMOgDCCg5WQuav4x9-aLt6hKAZHsWiS1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);